language: python
services:
  - docker
script:
- whoami
- pwd
- gcloud version || true
- if [ ! -d "$HOME/google-cloud-sdk/bin" ]; then rm -rf $HOME/google-cloud-sdk; export CLOUDSDK_CORE_DISABLE_PROMPTS=1; curl https://sdk.cloud.google.com | bash; fi
# Add gcloud to $PATH
- source /home/travis/google-cloud-sdk/path.bash.inc
- gcloud version
- docker pull debian:buster-slim
- docker tag debian:buster-slim us.gcr.io/objit-chris/chris-test:v1
- docker push us.gcr.io/objit-chris/chris-test:v1
cache:
  directories:
    - "$HOME/google-cloud-sdk/"
